### ISSUE TITLE
Type Error with UTF-8 encoding

### ISSUE THREAD

**Issue by csrajath** [brishti55/scholix_Bath#1]
I tried experimenting with the code base but am stuck with the below error:

Processing doi 10.1002/2015RS005781
Traceback (most recent call last):
  File "bath_dataset_lit_link.py", line 81, in <module>
    `**link_list.write(doi + '\t' + data_creators.encode("utf-8") + '\t' + lit_doi.encode("utf-8")+ '\t' + "Title: " + title.encode('utf-8') +"; Publisher: "+ pub_names.encode('utf-8') + "; Creators: "+ lit_creators.encode("utf-8") +'\n')`
TypeError: must be str, not bytes**

**Comment by csrajath** [comment]
> I tried experimenting with the code base but am stuck with the below error:
> 
> Processing doi 10.1002/2015RS005781
> Traceback (most recent call last):
> File "bath_dataset_lit_link.py", line 81, in
> `**link_list.write(doi + '\t' + data_creators.encode("utf-8") + '\t' + lit_doi.encode("utf-8")+ '\t' + "Title: " + title.encode('utf-8') +"; Publisher: "+ pub_names.encode('utf-8') + "; Creators: "+ lit_creators.encode("utf-8") +'\n')`
> TypeError: must be str, not bytes**

`link_list.write(str(doi) + '\t' + str(data_creators.encode("utf-8")) + '\t' + str(lit_doi.encode("utf-8"))+ '\t' + "Title: " + str(title.encode("utf-8")) +"; Publisher: "+ str(pub_names.encode("utf-8")) + "; Creators: "+ str(lit_creators.encode("utf-8")) +'\n')`
